"""add response_source to chat_messages

Revision ID: 29afeca44c18
Revises: 9daf689c085d
Create Date: 2026-02-05 20:09:01.600353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29afeca44c18'
down_revision: Union[str, Sequence[str], None] = '9daf689c085d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('response_source', sa.String(length=50), nullable=True))
    op.alter_column('chat_sessions', 'session_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('chat_sessions', 'message_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_chat_sessions_session_date'), 'chat_sessions', ['session_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_sessions_session_date'), table_name='chat_sessions')
    op.alter_column('chat_sessions', 'message_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('chat_sessions', 'session_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('chat_messages', 'response_source')
    # ### end Alembic commands ###
