"""initial

Revision ID: f66623cc91c7
Revises:
Create Date: 2026-01-19 20:44:00.415316

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f66623cc91c7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS menuitem (
            id SERIAL NOT NULL,
            text VARCHAR(255) NOT NULL,
            route VARCHAR(255),
            icon VARCHAR(255),
            item_order INTEGER,
            isdeleted BOOLEAN NOT NULL,
            PRIMARY KEY (id),
            UNIQUE (text)
        )
    """
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_menuitem_id ON menuitem (id)")

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS roles (
            id SERIAL NOT NULL,
            role VARCHAR(20) NOT NULL,
            created_at TIMESTAMP,
            updated_at TIMESTAMP,
            is_active BOOLEAN,
            is_deleted BOOLEAN,
            PRIMARY KEY (id),
            UNIQUE (role)
        )
    """
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_roles_id ON roles (id)")

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS menuitem_role (
            menuitem_id INTEGER NOT NULL,
            roles_id INTEGER NOT NULL,
            PRIMARY KEY (menuitem_id, roles_id),
            FOREIGN KEY (menuitem_id) REFERENCES menuitem (id),
            FOREIGN KEY (roles_id) REFERENCES roles (id)
        )
    """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS users (
            id SERIAL NOT NULL,
            firstname VARCHAR(50) NOT NULL,
            lastname VARCHAR(50) NOT NULL,
            username VARCHAR(50) NOT NULL,
            password VARCHAR(255) NOT NULL,
            role_id INTEGER NOT NULL,
            created_at TIMESTAMP,
            updated_at TIMESTAMP,
            is_active BOOLEAN,
            is_deleted BOOLEAN,
            PRIMARY KEY (id),
            FOREIGN KEY (role_id) REFERENCES roles (id)
        )
    """
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_users_id ON users (id)")
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS ix_users_username ON users (username)"
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS chat_sessions (
            id UUID NOT NULL,
            user_id INTEGER NOT NULL,
            title VARCHAR(255) NOT NULL,
            created_at TIMESTAMP,
            updated_at TIMESTAMP,
            PRIMARY KEY (id),
            FOREIGN KEY (user_id) REFERENCES users (id)
        )
    """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS chat_messages (
            id UUID NOT NULL,
            chat_session_id UUID NOT NULL,
            user_id INTEGER NOT NULL,
            message_type VARCHAR(20) NOT NULL,
            content TEXT NOT NULL,
            is_user BOOLEAN NOT NULL,
            timestamp TIMESTAMP,
            audio_url VARCHAR(500),
            image_url VARCHAR(500),
            PRIMARY KEY (id),
            FOREIGN KEY (chat_session_id) REFERENCES chat_sessions (id),
            FOREIGN KEY (user_id) REFERENCES users (id)
        )
    """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_chat_messages_chat_session_id ON chat_messages (chat_session_id)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_messages_chat_session_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_table("chat_sessions")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("menuitem_role")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_menuitem_id"), table_name="menuitem")
    op.drop_table("menuitem")
    # ### end Alembic commands ###
